name: safemap
description: Safe Map - Women's Safety Platform for India
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  go_router: ^12.1.3
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Network and API
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  socket_io_client: ^2.0.3+1
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  mapbox_maps_flutter: ^1.0.0
  google_maps_flutter: ^2.5.3
  
  # Device Features
  camera: ^0.10.5+9
  image_picker: ^1.0.4
  audio_waveforms: ^1.0.5
  record: ^5.0.4
  audioplayers: ^5.2.1
  video_player: ^2.8.1
  sensors_plus: ^4.0.2
  device_info_plus: ^9.1.1
  permission_handler: ^11.1.0
  
  # Security and Storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Biometrics and Authentication
  local_auth: ^2.1.7
  
  # Communication
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  contacts_service: ^0.6.3
  call_log: ^4.0.0
  sms_advanced: ^1.0.1
  telephony: ^0.2.0
  
  # Background Tasks
  workmanager: ^0.5.2
  flutter_background_service: ^5.0.5
  android_alarm_manager_plus: ^3.0.4
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # Cloud Storage
  firebase_storage: ^11.5.6
  
  # Voice and AI
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Analytics and Monitoring
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  sentry_flutter: ^7.13.2
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  
  # Utils
  uuid: ^4.2.1
  timeago: ^3.6.0
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  
  # Wearable Integration
  health: ^10.1.0
  wear: ^1.1.0
  
  # Indian Specific
  razorpay_flutter: ^1.3.6
  
  # Development
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: SafeMapIcons
      fonts:
        - asset: assets/fonts/SafeMapIcons.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n 